// Achievement definitions - scalable achievement catalog
import { Achievement, AchievementCategory, AchievementDifficulty } from "@/types/achievements";

const getDifficultyMultiplier = (difficulty: AchievementDifficulty): number => {
  const multipliers: Record<AchievementDifficulty, number> = {
    easy: 1,
    medium: 1.5,
    hard: 2,
    expert: 3,
  };
  return multipliers[difficulty];
};

export const ACHIEVEMENTS: Achievement[] = [
  // ===== DAILY ACHIEVEMENTS =====
  {
    id: "first_task_daily",
    name: "Morning Starter",
    description: "Complete your first task of the day",
    category: "daily",
    difficulty: "easy",
    icon: "Sun",
    basePoints: 5,
    difficultyMultiplier: getDifficultyMultiplier("easy"),
    condition: { type: "task_count", target: 1, metric: "daily" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "five_tasks_daily",
    name: "Daily Grinder",
    description: "Complete 5 tasks in a single day",
    category: "daily",
    difficulty: "medium",
    icon: "Zap",
    basePoints: 15,
    difficultyMultiplier: getDifficultyMultiplier("medium"),
    condition: { type: "task_count", target: 5, metric: "daily" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "ten_tasks_daily",
    name: "Beast Mode",
    description: "Complete 10 tasks in a single day",
    category: "daily",
    difficulty: "hard",
    icon: "Flame",
    basePoints: 30,
    difficultyMultiplier: getDifficultyMultiplier("hard"),
    condition: { type: "task_count", target: 10, metric: "daily" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "perfect_day",
    name: "Light Work",
    description: "Complete all tasks scheduled for today",
    category: "daily",
    difficulty: "medium",
    icon: "Target",
    basePoints: 20,
    difficultyMultiplier: getDifficultyMultiplier("medium"),
    condition: { type: "completion_rate", target: 100, metric: "daily" },
    unlocked: false,
    progress: 0,
    secret: false,
  },

  // ===== WEEKLY ACHIEVEMENTS =====
  {
    id: "three_day_streak",
    name: "Weekend Warrior",
    description: "Maintain a 3-day task completion streak",
    category: "weekly",
    difficulty: "easy",
    icon: "Calendar",
    basePoints: 15,
    difficultyMultiplier: getDifficultyMultiplier("easy"),
    condition: { type: "streak", target: 3, metric: "weekly" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "seven_day_streak",
    name: "Week Warrior",
    description: "Maintain a 7-day task completion streak",
    category: "weekly",
    difficulty: "hard",
    icon: "Award",
    basePoints: 50,
    difficultyMultiplier: getDifficultyMultiplier("hard"),
    condition: { type: "streak", target: 7, metric: "weekly" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "twenty_tasks_weekly",
    name: "Weekly Warrior",
    description: "Complete 20 tasks in a week",
    category: "weekly",
    difficulty: "medium",
    icon: "BookOpen",
    basePoints: 25,
    difficultyMultiplier: getDifficultyMultiplier("medium"),
    condition: { type: "task_count", target: 20, metric: "weekly" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "eighty_percent_weekly",
    name: "Consistency Plus",
    description: "Achieve 80% task completion rate in a week",
    category: "weekly",
    difficulty: "medium",
    icon: "TrendingUp",
    basePoints: 30,
    difficultyMultiplier: getDifficultyMultiplier("medium"),
    condition: { type: "completion_rate", target: 80, metric: "weekly" },
    unlocked: false,
    progress: 0,
    secret: false,
  },

  // ===== MONTHLY ACHIEVEMENTS =====
  {
    id: "fourteen_day_streak",
    name: "Learning Champion",
    description: "Maintain a 14-day task completion streak",
    category: "monthly",
    difficulty: "hard",
    icon: "Crown",
    basePoints: 75,
    difficultyMultiplier: getDifficultyMultiplier("hard"),
    condition: { type: "streak", target: 14, metric: "monthly" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "hundred_tasks_monthly",
    name: "Month Master",
    description: "Complete 100 tasks in a month",
    category: "monthly",
    difficulty: "expert",
    icon: "Star",
    basePoints: 100,
    difficultyMultiplier: getDifficultyMultiplier("expert"),
    condition: { type: "task_count", target: 100, metric: "monthly" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "ninety_percent_monthly",
    name: "Perfection Seeker",
    description: "Achieve 90% task completion rate in a month",
    category: "monthly",
    difficulty: "hard",
    icon: "CheckCircle",
    basePoints: 60,
    difficultyMultiplier: getDifficultyMultiplier("hard"),
    condition: { type: "completion_rate", target: 90, metric: "monthly" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "thirty_day_streak",
    name: "Unstoppable",
    description: "Maintain a 30-day task completion streak",
    category: "monthly",
    difficulty: "expert",
    icon: "Zap",
    basePoints: 150,
    difficultyMultiplier: getDifficultyMultiplier("expert"),
    condition: { type: "streak", target: 30, metric: "monthly" },
    unlocked: false,
    progress: 0,
    secret: true, // Hidden until unlocked
  },

  // ===== TIMELESS ACHIEVEMENTS (All-time) =====
  {
    id: "first_task",
    name: "Journey Begins",
    description: "Complete your first task ever",
    category: "timeless",
    difficulty: "easy",
    icon: "Play",
    basePoints: 10,
    difficultyMultiplier: getDifficultyMultiplier("easy"),
    condition: { type: "task_count", target: 1, metric: "allTime" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "ten_tasks_alltime",
    name: "Task Master",
    description: "Complete 10 tasks total",
    category: "timeless",
    difficulty: "easy",
    icon: "Trophy",
    basePoints: 15,
    difficultyMultiplier: getDifficultyMultiplier("easy"),
    condition: { type: "task_count", target: 10, metric: "allTime" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "fifty_tasks_alltime",
    name: "Task Enthusiast",
    description: "Complete 50 tasks total",
    category: "timeless",
    difficulty: "medium",
    icon: "BookOpen",
    basePoints: 40,
    difficultyMultiplier: getDifficultyMultiplier("medium"),
    condition: { type: "task_count", target: 50, metric: "allTime" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "hundred_tasks_alltime",
    name: "Productivity Pro",
    description: "Complete 100 tasks total",
    category: "timeless",
    difficulty: "hard",
    icon: "Target",
    basePoints: 75,
    difficultyMultiplier: getDifficultyMultiplier("hard"),
    condition: { type: "task_count", target: 100, metric: "allTime" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "five_hundred_tasks_alltime",
    name: "Legend",
    description: "Complete 500 tasks total",
    category: "timeless",
    difficulty: "expert",
    icon: "Crown",
    basePoints: 200,
    difficultyMultiplier: getDifficultyMultiplier("expert"),
    condition: { type: "task_count", target: 500, metric: "allTime" },
    unlocked: false,
    progress: 0,
    secret: true,
  },
  {
    id: "eighty_percent_alltime",
    name: "Consistency King",
    description: "Achieve 80% completion rate overall",
    category: "timeless",
    difficulty: "medium",
    icon: "Heart",
    basePoints: 50,
    difficultyMultiplier: getDifficultyMultiplier("medium"),
    condition: { type: "completion_rate", target: 80, metric: "allTime" },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "one_thousand_points",
    name: "Point Master",
    description: "Earn 1000 achievement points",
    category: "timeless",
    difficulty: "expert",
    icon: "Sparkles",
    basePoints: 100,
    difficultyMultiplier: getDifficultyMultiplier("expert"),
    condition: { type: "points", target: 1000, metric: "allTime" },
    unlocked: false,
    progress: 0,
    secret: false,
  },

  // ===== USAGE-BASED ACHIEVEMENTS =====
  {
    id: "early_bird",
    name: "Early Bird",
    description: "Complete a task before 8 AM",
    category: "timeless",
    difficulty: "easy",
    icon: "Sunrise",
    basePoints: 5,
    difficultyMultiplier: getDifficultyMultiplier("easy"),
    condition: { type: "custom", target: 1 },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "night_owl",
    name: "Night Owl",
    description: "Complete a task after 10 PM",
    category: "timeless",
    difficulty: "easy",
    icon: "Moon",
    basePoints: 5,
    difficultyMultiplier: getDifficultyMultiplier("easy"),
    condition: { type: "custom", target: 1 },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "speed_demon",
    name: "Speed Demon",
    description: "Complete 10 tasks before their due date",
    category: "timeless",
    difficulty: "medium",
    icon: "Zap",
    basePoints: 35,
    difficultyMultiplier: getDifficultyMultiplier("medium"),
    condition: { type: "custom", target: 10 },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "comeback_king",
    name: "Comeback King",
    description: "Restart a 7+ day streak after breaking it",
    category: "timeless",
    difficulty: "hard",
    icon: "RotateCcw",
    basePoints: 45,
    difficultyMultiplier: getDifficultyMultiplier("hard"),
    condition: { type: "custom", target: 1 },
    unlocked: false,
    progress: 0,
    secret: false,
  },
  {
    id: "all_nighter",
    name: "All Nighter",
    description: "Be logged in for 12+ hours in one day",
    category: "timeless",
    difficulty: "medium",
    icon: "Clock",
    basePoints: 25,
    difficultyMultiplier: getDifficultyMultiplier("medium"),
    condition: { type: "usage_time", target: 12 },
    unlocked: false,
    progress: 0,
    secret: false,
  },
];

// Achievement levels system
export const ACHIEVEMENT_LEVELS = [
  {
    level: 1,
    name: "Novice",
    requiredPoints: 0,
    icon: "Zap",
    color: "gray",
  },
  {
    level: 2,
    name: "Apprentice",
    requiredPoints: 100,
    icon: "Flame",
    color: "blue",
  },
  {
    level: 3,
    name: "Journeyman",
    requiredPoints: 300,
    icon: "Star",
    color: "purple",
  },
  {
    level: 4,
    name: "Expert",
    requiredPoints: 750,
    icon: "Crown",
    color: "gold",
  },
  {
    level: 5,
    name: "Master",
    requiredPoints: 1500,
    icon: "Trophy",
    color: "orange",
  },
  {
    level: 6,
    name: "Legend",
    requiredPoints: 3000,
    icon: "Zap",
    color: "red",
  },
];
